package br.org.catolicasc.pug.helpers.builders;

import br.org.catolicasc.pug.helpers.TestNameGenerator;
import br.org.catolicasc.pug.partner.domain.Entity;
import br.org.catolicasc.pug.partner.domain.vos.Cnpj;
import java.util.Random;
import java.util.UUID;

/**
 * Builder class for creating {@link Entity} domain aggregates in test scenarios.
 *
 * <p>Provides a fluent API to define partner entity properties, including geographic location and
 * CNPJ validation, with random unique names generated by default.
 */
public class EntityBuilder {
  private final String name = TestNameGenerator.generateRandomEntityName();
  private String cnpj = generateValidCnpj();
  private UUID cityId;

  private EntityBuilder() {}

  /**
   * Initializes a new instance of the EntityBuilder.
   *
   * @return a new EntityBuilder instance
   */
  public static EntityBuilder anEntity() {
    return new EntityBuilder();
  }

  /**
   * Sets the city identifier linked to this partner entity.
   *
   * @param cityId the UUID of the {@link br.org.catolicasc.pug.geo.domain.City}
   * @return this builder instance
   */
  public EntityBuilder withCity(UUID cityId) {
    this.cityId = cityId;
    return this;
  }

  /**
   * Sets the CNPJ for this partner entity.
   *
   * @param cnpj the CNPJ string
   * @return this builder instance
   */
  public EntityBuilder withCnpj(String cnpj) {
    this.cnpj = cnpj;
    return this;
  }

  /**
   * Generates a valid random CNPJ based on standard Brazilian validation rules.
   *
   * @return a valid CNPJ string
   */
  private String generateValidCnpj() {
    int[] cnpj = new int[14];
    Random random = new Random();
    for (int i = 0; i < 12; i++) {
      cnpj[i] = random.nextInt(10);
    }
    int[] weight1 = {5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2};
    cnpj[12] = calculateDigit(cnpj, weight1);
    int[] weight2 = {6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2};
    cnpj[13] = calculateDigit(cnpj, weight2);

    StringBuilder sb = new StringBuilder();
    for (int digit : cnpj) {
      sb.append(digit);
    }
    return sb.toString();
  }

  /**
   * Calculates the verification digit for the CNPJ algorithm.
   *
   * @param cnpj the array of digits
   * @param weights the weight array
   * @return the calculated check digit
   */
  private int calculateDigit(int[] cnpj, int[] weights) {
    int sum = 0;
    for (int i = 0; i < weights.length; i++) {
      sum += cnpj[i] * weights[i];
    }
    int remainder = sum % 11;
    return (remainder < 2) ? 0 : 11 - remainder;
  }

  /**
   * Constructs the {@link Entity} aggregate using the current builder state.
   *
   * @return a configured {@link Entity} instance
   * @throws IllegalStateException if cityId has not been set
   */
  public Entity build() {
    if (cityId == null)
      throw new IllegalStateException("CityId must be provided from an existing city");
    return Entity.factory(Cnpj.factory(cnpj), name, cityId, "Address");
  }
}
