services:
  # ── DEV CONTAINERS ────────────────────────────────────────────────────────
  postgres:
    image: registry-docker.weg.net/postgres:16
    container_name: pug-postgres
    ports: [ "5433:5432" ]
    environment:
      POSTGRES_USER: pug
      POSTGRES_PASSWORD: pug
      POSTGRES_DB: pug
    networks: [ pug-network ]

  mongodb:
    image: registry-docker.weg.net/mongo:7.0
    container_name: pug-mongodb
    ports: [ "27018:27017" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: pug
      MONGO_INITDB_ROOT_PASSWORD: pug
    networks: [ pug-network ]

networks:
  pug-network:
    driver: bridge