# ------------------------------ BASE SETTINGS ------------------------------
quarkus.application.name=pug-service
quarkus.application.version=0.7.0-SNAPSHOT
quarkus.application.ui-header={applicationName} - {applicationVersion}
# Java & Localization Defaults
quarkus.default-locale=pt-BR
quarkus.log.level=INFO
# Datasource & ORM (General)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=16.0
# JSON (Jackson) Behaviors
quarkus.jackson.write-dates-as-timestamps=false
quarkus.jackson.fail-on-unknown-properties=false
# Console & logs (General)
quarkus.console.color=true
quarkus.log.metrics.enabled=true
# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
# HTTP & CORS (Base)
quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type
quarkus.http.cors.access-control-max-age=PT24H
quarkus.http.cors.access-control-allow-credentials=true
# OpenAPI / Swagger
quarkus.smallrye-openapi.info-title=PUG Service API
quarkus.smallrye-openapi.info-version={applicationVersion}
quarkus.smallrye-openapi.info-description=Endpoints for Universidade Gratuita platform
quarkus.swagger-ui.always-include=true
# Hibernate Search + ES (Base)
quarkus.hibernate-search-orm.elasticsearch.version=9
quarkus.hibernate-search-orm.elasticsearch.analysis.configurer=com.pug.shared.infra.search.EsAnalysis