# ------------------------------ QA SETTINGS ------------------------------
# Profile definition
quarkus.profile=qa

# Logging and observability
quarkus.log.category."br.org.catolicasc.pug".level=INFO
quarkus.log.console.level=INFO
quarkus.log.min-level=INFO
quarkus.console.color=false
quarkus.log.console.json=false
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %r -> %s (%Ds) [user: %u] [cid: %{o,X-Correlation-Id}]
quarkus.http.access-log.exclude-pattern=/q/.*

# Proxy and HTTP
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:none}
quarkus.http.record-request-start-time=true

# OpenAPI and Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Datasource and resiliency
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}
quarkus.datasource.jdbc.min-size=3
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.acquisition-timeout=PT10S
quarkus.datasource.jdbc.background-validation-interval=PT30S

# MongoDB
quarkus.mongodb.connection-string=${MONGODB_URI}
quarkus.mongodb.database=pug_audit

# JWT signing and verification
smallrye.jwt.sign.key=${JWT_SECRET_KEY}
mp.jwt.verify.publickey=${JWT_SECRET_KEY}

# Application secrets
security.password.pepper=${PASSWORD_PEPPER}
security.qr.pepper=${QR_PEPPER}

# Application specific settings
pug.seed.passwords.enabled=true