# ------------------------------ BASE SETTINGS ------------------------------
quarkus.application.name=pug-service
quarkus.application.version=0.7.0-SNAPSHOT
quarkus.application.ui-header={applicationName} - {applicationVersion}
# Java & Localization Defaults
quarkus.default-locale=pt-BR
quarkus.log.level=INFO
# Datasource & ORM (General)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=16.0
# Fix for UUID encoding in MongoDB
quarkus.mongodb.uuid-representation=standard
# JSON (Jackson) Behaviors
quarkus.jackson.write-dates-as-timestamps=false
quarkus.jackson.fail-on-unknown-properties=false
# Console & logs (General)
quarkus.console.color=true
quarkus.log.metrics.enabled=true
# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
# HTTP & CORS (Base)
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type
quarkus.http.cors.access-control-max-age=PT24H
quarkus.http.cors.access-control-allow-credentials=true
# OpenAPI / Swagger
quarkus.smallrye-openapi.info-title=PUG Service API
quarkus.smallrye-openapi.info-version={applicationVersion}
quarkus.smallrye-openapi.info-description=Endpoints for Universidade Gratuita platform
quarkus.swagger-ui.always-include=true
# Hibernate Search + ES (Base)
quarkus.hibernate-search-orm.elasticsearch.version=9
quarkus.hibernate-search-orm.elasticsearch.analysis.configurer=br.org.catolicasc.pug.shared.infra.search.EsAnalysis
# SECURITY & JWT
# O emissor do token (identifica??o da sua API)
mp.jwt.verify.issuer=https://api.pug.com
smallrye.jwt.new-token.issuer=https://api.pug.com
# Algoritmo sim?trico (usa uma ?nica string secreta para assinar e validar)
smallrye.jwt.new-token.signature-algorithm=HS256
mp.jwt.verify.publickey.algorithm=HS256
# Tempo de vida do token (ex: 28800 segundos = 8 horas)
smallrye.jwt.new-token.lifespan=28800
# A chave secreta codificada em Base64 (Deve ter pelo menos 256 bits / 32 bytes)
# (Esta chave ? apenas para DEV. Em PROD, sobrescreveremos com vari?vel de ambiente)
smallrye.jwt.sign.key={"kty":"oct","k":"cHVnLXNlY3JldC1rZXktZm9yLWp3dC1zaWduYXR1cmUtMjAyNg"}
mp.jwt.verify.publickey={"kty":"oct","k":"cHVnLXNlY3JldC1rZXktZm9yLWp3dC1zaWduYXR1cmUtMjAyNg"}
