# ------------------------------ ALL PROFILES ------------------------------
quarkus.application.name=pug-service
quarkus.application.version=0.1.4-SNAPSHOT
quarkus.application.ui-header={applicationName} - {applicationVersion}
# Datasource & ORM
quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=16.0
# Dev UI (applies only when Dev UI is active)
quarkus.datasource.dev-ui.allow-sql=true
# Console & logs
quarkus.console.color=true
quarkus.log.metrics.enabled=true
quarkus.log.category."com.pug".level=DEBUG
quarkus.log.console.level=DEBUG
quarkus.log.console.darken=1
# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
# HTTP & CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=none
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true
# OpenAPI / Swagger
quarkus.smallrye-openapi.info-title=PUG Service API
quarkus.smallrye-openapi.info-version=0.1.4-SNAPSHOT
quarkus.smallrye-openapi.info-description=Endpoints for Universidade Gratuita platform
quarkus.swagger-ui.always-include=true
# Hibernate Search + ES
quarkus.hibernate-search-orm.elasticsearch.version=9
quarkus.hibernate-search-orm.elasticsearch.analysis.configurer=com.pug.shared.infra.search.EsAnalysis
# ------------------------------ DEV PROFILE ------------------------------
# Datasource & ORM
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.image-name=postgres:16
%dev.quarkus.datasource.devservices.port=5433
%dev.quarkus.datasource.devservices.db-name=pug
%dev.quarkus.datasource.devservices.username=pug
%dev.quarkus.datasource.devservices.password=pug
%dev.quarkus.datasource.devservices.reuse=true
# HTTP & CORS
%dev.quarkus.http.cors.origins=/.*/
# Hibernate Search + ES
%dev.quarkus.elasticsearch.devservices.port=9201
%dev.quarkus.elasticsearch.devservices.image-name=docker.io/elastic/elasticsearch:9.1.5
%dev.quarkus.hibernate-search-orm.schema-management.strategy=create-or-validate
%dev.quarkus.hibernate-search-orm.indexing.plan.synchronization.strategy=sync
# Security
%dev.security.password.pepper=dev-only-32+chars-secret
# ------------------------------ PROD PROFILE ------------------------------
# Datasource & ORM
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASS}
# Console & logs
%prod.quarkus.log.category."com.pug".level=INFO
%prod.quarkus.log.console.level=INFO
%prod.quarkus.log.min-level=INFO
# Hibernate Search + ES
%prod.quarkus.hibernate-search-orm.elasticsearch.hosts=es1.example:9200,es2.example:9200
%prod.quarkus.hibernate-search-orm.elasticsearch.protocol=https
%prod.quarkus.hibernate-search-orm.elasticsearch.username=${ES_USER}
%prod.quarkus.hibernate-search-orm.elasticsearch.password=${ES_PASS}
%prod.quarkus.hibernate-search-orm.schema-management.strategy=validate