# ------------------------------ DEV SETTINGS ------------------------------
# Logging & Terminal
quarkus.log.category."com.pug".level=DEBUG
quarkus.log.console.level=DEBUG
quarkus.log.console.darken=0
# Observabilidade de Banco (Hibernate/SQL)
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
# Dev UI & Testing
quarkus.datasource.dev-ui.allow-sql=true
quarkus.test.continuous-testing=paused
# Datasource & DevServices (PostgreSQL)
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.image-name=postgres:16
quarkus.datasource.devservices.port=5433
quarkus.datasource.devservices.db-name=pug
quarkus.datasource.devservices.username=pug
quarkus.datasource.devservices.password=pug
quarkus.datasource.devservices.reuse=true
# Hibernate Search + ES DevServices
quarkus.elasticsearch.devservices.port=9201
quarkus.elasticsearch.devservices.image-name=docker.io/elastic/elasticsearch:9.1.5
quarkus.elasticsearch.devservices.timeout=60S
quarkus.hibernate-search-orm.schema-management.strategy=create-or-validate
quarkus.hibernate-search-orm.indexing.plan.synchronization.strategy=sync
# HTTP, CORS & Swagger UI
quarkus.http.cors.origins=/.*/
quarkus.swagger-ui.path=/swagger-ui
quarkus.http.record-request-start-time=true
# Security
security.password.pepper=dev-only-32+chars-secret