# ------------------------------ PROD SETTINGS ------------------------------
# Profile definition
quarkus.profile=prod

# Logging and observability
quarkus.log.category."br.org.catolicasc.pug".level=INFO
quarkus.log.console.level=INFO
quarkus.log.min-level=INFO
quarkus.console.color=false
quarkus.log.console.json=true

# Proxy and HTTP
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.cors.origins=${CORS_ORIGINS:none}
quarkus.swagger-ui.always-include=false

# Datasource and resiliency
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.acquisition-timeout=PT10S
quarkus.datasource.jdbc.background-validation-interval=PT30S
quarkus.flyway.placeholders.seed_test_data_enabled=false

# MongoDB
quarkus.mongodb.connection-string=${MONGODB_URI}
quarkus.mongodb.database=pug_audit

# JWT signing and verification
smallrye.jwt.sign.key=${JWT_SECRET_KEY}
mp.jwt.verify.publickey=${JWT_SECRET_KEY}

# Application secrets
security.password.pepper=${PASSWORD_PEPPER}
security.qr.pepper=${QR_PEPPER}

# Application specific settings
pug.seed.passwords.enabled=false