# ------------------------------ DEV SETTINGS ------------------------------
# Logging & Terminal
quarkus.log.category."com.pug".level=DEBUG
quarkus.log.console.level=DEBUG
quarkus.log.console.darken=0
quarkus.log.console.json=false
# Observabilidade de Banco (Hibernate/SQL)
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
# Dev UI & Testing
quarkus.datasource.dev-ui.allow-sql=true
quarkus.test.continuous-testing=paused
# --- DISABLE DEVSERVICES (Use local Docker-Compose instead) ---
quarkus.datasource.devservices.enabled=false
quarkus.mongodb.devservices.enabled=false
quarkus.elasticsearch.devservices.enabled=false
# Datasource (PostgreSQL on 5433)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/pug
quarkus.datasource.username=pug
quarkus.datasource.password=pug
# MongoDB (on 27018)
quarkus.mongodb.connection-string=mongodb://pug:pug@localhost:27018
quarkus.mongodb.database=pug_audit
# Hibernate Search + ES (on 9201)
quarkus.hibernate-search-orm.elasticsearch.hosts=localhost:9201
quarkus.hibernate-search-orm.schema-management.strategy=create-or-validate
quarkus.hibernate-search-orm.indexing.plan.synchronization.strategy=sync
# HTTP, CORS & Swagger UI
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.swagger-ui.path=/swagger-ui
quarkus.http.record-request-start-time=true
# Security
security.password.pepper=dev-only-32+chars-secret
security.qr.pepper=dev-only-32+chars-secret