# ------------------------------ PROD SETTINGS ------------------------------
# Profile Definition
quarkus.profile=prod
# Logging & Observability
quarkus.log.category."com.pug".level=INFO
quarkus.log.console.level=INFO
quarkus.log.min-level=INFO
quarkus.console.color=false
quarkus.log.console.json=true
# Proxy & Security
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.cors.origins=${CORS_ORIGINS:none}
quarkus.swagger-ui.always-include=false
# Datasource & Resiliency
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.acquisition-timeout=PT10S
quarkus.datasource.jdbc.background-validation-interval=PT30S
# Security (Application Secrets & JWT)
smallrye.jwt.sign.key=${JWT_SECRET_KEY}
mp.jwt.verify.publickey=${JWT_SECRET_KEY}
security.password.pepper=${PASSWORD_PEPPER}
security.qr.pepper=${QR_PEPPER}
# Hibernate Search + ES (Production Cluster)
quarkus.hibernate-search-orm.elasticsearch.hosts=${ES_HOSTS}
quarkus.hibernate-search-orm.elasticsearch.protocol=https
quarkus.hibernate-search-orm.elasticsearch.username=${ES_USER}
quarkus.hibernate-search-orm.elasticsearch.password=${ES_PASS}
quarkus.hibernate-search-orm.schema-management.strategy=validate