package br.org.catolicasc.pug.helpers.builders.domain;

import br.org.catolicasc.pug.helpers.TestBrazilianIdentifierGenerator;
import br.org.catolicasc.pug.helpers.TestNameGenerator;
import br.org.catolicasc.pug.partner.domain.Entity;
import br.org.catolicasc.pug.partner.domain.vos.Cnpj;
import java.util.UUID;

/**
 * Builder class for creating {@link Entity} domain aggregates in test scenarios.
 *
 * <p>Provides a fluent API to define partner entity properties, including geographic location and
 * CNPJ validation, with random unique names generated by default.
 */
public class EntityBuilder {
  private final String name = TestNameGenerator.generateRandomEntityName();
  private String cnpj = TestBrazilianIdentifierGenerator.generateValidCnpj();
  private UUID cityId;

  private EntityBuilder() {}

  /**
   * Initializes a new instance of the EntityBuilder.
   *
   * @return a new EntityBuilder instance
   */
  public static EntityBuilder anEntity() {
    return new EntityBuilder();
  }

  /**
   * Sets the city identifier linked to this partner entity.
   *
   * @param cityId the UUID of the {@link br.org.catolicasc.pug.geo.domain.City}
   * @return this builder instance
   */
  public EntityBuilder withCity(UUID cityId) {
    this.cityId = cityId;
    return this;
  }

  /**
   * Sets the CNPJ for this partner entity.
   *
   * @param cnpj the CNPJ string
   * @return this builder instance
   */
  public EntityBuilder withCnpj(String cnpj) {
    this.cnpj = cnpj;
    return this;
  }

  /**
   * Constructs the {@link Entity} aggregate using the current builder state.
   *
   * @return a configured {@link Entity} instance
   * @throws IllegalStateException if cityId has not been set
   */
  public Entity build() {
    if (cityId == null)
      throw new IllegalStateException("CityId must be provided from an existing city");
    return Entity.factory(Cnpj.factory(cnpj), name, cityId, "Address");
  }
}
