package br.org.catolicasc.pug.helpers.builders.domain;

import br.org.catolicasc.pug.academic.domain.FormerStudent;
import br.org.catolicasc.pug.academic.domain.vos.AcademicRegistration;
import br.org.catolicasc.pug.academic.domain.vos.CounterpartHours;
import br.org.catolicasc.pug.academic.domain.vos.Period;
import br.org.catolicasc.pug.helpers.TestNameGenerator;
import br.org.catolicasc.pug.shared.domain.enums.Campi;
import com.github.f4b6a3.uuid.UuidCreator;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Random;
import java.util.UUID;

/**
 * Builder class for creating {@link FormerStudent} domain aggregates in test scenarios.
 *
 * <p>Provides a fluent API to define formerStudent properties, including academic details, campus
 * assignment, and course enrollment, with random unique values generated by default.
 */
public class FormerStudentBuilder {
  private UUID accountId = UuidCreator.getTimeOrderedEpoch();
  private final String registration = TestNameGenerator.generateUniqueRegistration();
  private Campi campus = getRandomCampus();
  private UUID courseId = UuidCreator.getTimeOrderedEpoch();

  private FormerStudentBuilder() {}

  /**
   * Initializes a new instance of the FormerStudentBuilder.
   *
   * @return a new FormerStudentBuilder instance
   */
  public static FormerStudentBuilder aStudent() {
    return new FormerStudentBuilder();
  }

  /**
   * Helper to retrieve a random university campus.
   *
   * @return a randomly selected {@link Campi}
   */
  private Campi getRandomCampus() {
    Campi[] values = Campi.values();
    return values[new Random().nextInt(values.length)];
  }

  /**
   * Sets the account identifier linked to this formerStudent.
   *
   * @param accountId the UUID of the account
   * @return this builder instance
   */
  public FormerStudentBuilder withAccountId(UUID accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Sets the course identifier for the formerStudent enrollment.
   *
   * @param courseId the UUID of the course
   * @return this builder instance
   */
  public FormerStudentBuilder withCourse(UUID courseId) {
    this.courseId = courseId;
    return this;
  }

  /**
   * Sets the campus jurisdiction for this formerStudent.
   *
   * @param campus the university {@link Campi}
   * @return this builder instance
   */
  public FormerStudentBuilder withCampus(Campi campus) {
    this.campus = campus;
    return this;
  }

  /**
   * Constructs the {@link FormerStudent} aggregate using the current builder state, applying default
   * academic periods and hour requirements.
   *
   * @return a configured {@link FormerStudent} instance
   */
  public FormerStudent build() {
    return FormerStudent.factory(
        accountId,
        AcademicRegistration.factory(registration),
        campus,
        courseId,
        CounterpartHours.factory(new BigDecimal("100"), BigDecimal.ZERO, false),
        Period.factory(LocalDate.now(), LocalDate.now().plusMonths(6)));
  }
}

