package br.org.catolicasc.pug.helpers.builders.domain;

import br.org.catolicasc.pug.helpers.TestNameGenerator;
import br.org.catolicasc.pug.project.domain.Project;
import com.github.f4b6a3.uuid.UuidCreator;
import java.math.BigDecimal;
import java.util.UUID;

/**
 * Builder class for creating {@link Project} domain aggregates in test scenarios.
 *
 * <p>Provides a fluent API to define project properties, such as the entity owner and creator, with
 * random unique names generated by default.
 */
public class ProjectBuilder {
  private String name = TestNameGenerator.generateRandomProjectName();
  private UUID entityId = UuidCreator.getTimeOrderedEpoch();
  private UUID creatorId = UuidCreator.getTimeOrderedEpoch();
  private final BigDecimal offeredHours = new BigDecimal("40.0");

  private ProjectBuilder() {}

  /**
   * Initializes a new instance of the ProjectBuilder.
   *
   * @return a new ProjectBuilder instance
   */
  public static ProjectBuilder aProject() {
    return new ProjectBuilder();
  }

  /**
   * Sets the title or name of the project.
   *
   * @param name the project name
   * @return this builder instance
   */
  public ProjectBuilder withName(String name) {
    this.name = name;
    return this;
  }

  /**
   * Sets the entity identifier offering the project.
   *
   * @param entityId the UUID of the partner entity
   * @return this builder instance
   */
  public ProjectBuilder withEntity(UUID entityId) {
    this.entityId = entityId;
    return this;
  }

  /**
   * Sets the creator identifier for the project.
   *
   * @param creatorId the UUID of the staff account who created the project
   * @return this builder instance
   */
  public ProjectBuilder withCreator(UUID creatorId) {
    this.creatorId = creatorId;
    return this;
  }

  /**
   * Constructs the {@link Project} aggregate using the current builder state.
   *
   * @return a configured {@link Project} instance
   */
  public Project build() {
    return Project.factory(
        name, entityId, "Project description", creatorId, 20, offeredHours, BigDecimal.ZERO);
  }
}
